version: "3.4"
services:
  api:
    container_name: clipboard_api
    build:
      target: prod
      context: .
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    links:
      - sqlite3

  sqlite3:
    container_name: sqlite3
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - "./db/sqlite3:/root/db"
    env_file:
      - docker.env
    ports:
      - '9000:9000'
    restart: unless-stopped
